//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use super::{
    schoology_link::Entity as SchoologyLink,
    schoology_request_tokens::Entity as SchoologyRequestTokens, sessions::Entity as Sessions,
    users::Entity as Users,
};
